name: PR test suite
trigger:
  change:
    types: [submit, create, push]
    branches: [main, ve-main, branch-*]
    paths:
    - "!.github/**"
    - "!.vscode/**"
    - "!benchmarking/**"
    - "!ci/**"
    - "!docs/**"
    - "!tools/**"
    - "!tutorials/**"
    - "!**/*.md"
    - "!*.md"
    - "!*.rst"
    - "!.gitignore"
    - "!LICENSE"
    - "!**/las/**"
    - "!Makefile"
    - "!**/test-las.yaml"

jobs:
  daft_on_native: &daft
    image: none
    working-directory: "/data00/codebase/daft/${{random_string(5)}}"
    envs:
      DAFT_ANALYTICS_ENABLED: '0'
      RUST_BACKTRACE: 1
      DAFT_RUNNER: native
      DAFT_FLOTILLA: 0
      DAFT_DASHBOARD_SKIP_BUILD: "true"
      TF_FORCE_GPU_ALLOW_GROWTH: "true"
    runs-on:
      cluster: "gpu"
      linux: {}
    steps:
    - uses: actions/setup-proxy

    - name: Check pre-commit
      commands:
      - pre-commit run --files .pre-commit-config.yaml

    - name: Build library and Test with pytest (Linux)
      commands:
      # Set HF_ENDPOINT to use a mirror to speed up the test when connecting to HuggingFace
      # Set http_proxy, https_proxy, no_proxy to empty to avoid using proxy when running the openai tests
      - export HF_ENDPOINT=https://hf-mirror.com && export http_proxy=http://sys-proxy-rd-relay.byted.org:8118 && export https_proxy=http://sys-proxy-rd-relay.byted.org:8118 && export no_proxy=code.byted.org && make ve-test

    - name: clean resources
      if: "${{always()}}"
      commands:
      - rm -rf $PWD

  daft_on_ray:
    <<: *daft
    envs:
      DAFT_ANALYTICS_ENABLED: '0'
      RUST_BACKTRACE: 1
      DAFT_RUNNER: ray
      DAFT_FLOTILLA: 1
      DAFT_DASHBOARD_SKIP_BUILD: "true"
      TF_FORCE_GPU_ALLOW_GROWTH: "true"
