name: Las Operator Test
trigger:
  change:
    types: [submit, create, push]
    branches: [main, ve-main]
    paths:
    - "**/las/**"
    - "**/test-las.yaml"

jobs:
  daft_on_ray:
    name: Unit Test
    image: none
    working-directory: "/data00/codebase/daft/${{random_string(5)}}"
    envs:
      DAFT_ANALYTICS_ENABLED: '0'
      RUST_BACKTRACE: 1
      DAFT_RUNNER: ray
      DAFT_FLOTILLA: 0
      NUM_GPUS: 8
      FORCE_QWENVL_VIDEO_READER: torchvision
    runs-on:
      cluster: "gpu"
      linux: {}
    steps:
    - name: Check pre-commit
      commands:
      - pre-commit run --files .pre-commit-config.yaml

    - name: Build library and Test with pytest (Linux)
      commands:
      - export TOS_ENDPOINT=${{TOS_ENDPOINT}}
      - export TOS_ACCESS_KEY=${{TOS_ACCESS_KEY}}
      - export TOS_SECRET_KEY=${{TOS_SECRET_KEY}}
      - export ARK_ACCESS_KEY=${{ARK_ACCESS_KEY}}
      - export ARK_SECRET_KEY=${{ARK_SECRET_KEY}}
      - export ARK_BASE_URL=${{ARK_BASE_URL}}
      - export VISUAL_SERVICE_ACCESS_KEY=${{VISUAL_SERVICE_ACCESS_KEY}}
      - export VISUAL_SERVICE_SECRET_KEY=${{VISUAL_SERVICE_SECRET_KEY}}
      - make test-las

    - name: clean resources
      if: "${{always()}}"
      commands:
      - rm -rf $PWD

#  daft_on_native:
#    <<: *daft
#    envs:
#      DAFT_ANALYTICS_ENABLED: '0'
#      RUST_BACKTRACE: 1
#      DAFT_RUNNER: native
