ARG BASE_IMAGE="nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04"
FROM ${BASE_IMAGE}

ARG INSTALL_DIR=/opt/
ARG PYTHON_VERSION=3.11
ENV TZ=Asia/Shanghai
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

USER root
ENV HOME=/root

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime\
    && apt update -y \
    && apt install -y wget vim git tzdata unzip sudo iputils-ping curl telnet openssh-server openssh-client software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && apt clean \
    && PY_V=$(echo $PYTHON_VERSION | sed 's;\.;;g') \
    && wget "https://repo.anaconda.com/miniconda/Miniconda3-py${PY_V}_25.1.1-2-Linux-x86_64.sh" --quiet  -O /tmp/miniconda.sh \
    && /bin/bash /tmp/miniconda.sh -b -u -p ${INSTALL_DIR}/conda \
    && ${INSTALL_DIR}/conda/bin/conda init \
    # Overwrite the follow files to solve system compatible issue,
    # see: https://github.com/luigifreda/pyslam/issues/133 is a example
    && cp /usr/lib/x86_64-linux-gnu/libgcc_s.so.1  /opt/conda/lib/ \
    && cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/conda/lib/ \
    && rm /tmp/miniconda.sh  \
    && ${INSTALL_DIR}/conda/bin/conda clean -y --all

ENV CONDA_HOME=${INSTALL_DIR}/conda
ENV PATH=$CONDA_HOME/bin:$PATH

WORKDIR $HOME
